#!/usr/bin/env python3

from random import random, randrange

def random_word():
	length = randrange(4, 10)
	
	vowels = "aeiou"
	consonants = "bcdfghjklmnpqrstvwxyz"

	cap = ""

	## 50/50 chance to start with a vowel
	nextvowel = randrange(100) > 50 and True or False

	for i in range(length):
		if nextvowel:
			cap += vowels[randrange(len(vowels))]
			if len(cap) >= 2:
				if cap[-2] in vowels:
					nextvowel = False
				else:
					nextvowel = randrange(100) > 50 and True or False
			else:
				nextvowel = randrange(100) > 50 and True or False
		else:
			cap += consonants[randrange(len(consonants))]
			if len(cap) >= 2:
				if cap[-2] in consonants:
					nextvowel = True
				else:
					nextvowel = randrange(100) > 50 and True or False
			else:
				nextvowel = randrange(100) > 50 and True or False
	
	cap = cap[0].upper() + cap[1:]
	return cap

for i in range(30):
	if randrange(100) < 50:
		# Get a county, township, or state.
		f = randrange(100) > 50 and "counties" or "cities"

		lines = open(f, "r").readlines()

		word = lines[randrange(len(lines))].strip().replace(" County", "")
	else:
		# Generate a completely random word.
		word = random_word()
	
	print(word.ljust(15), end="")

	if i % 3 == 0:
		print()

print()

